### ISSUE TITLE
Request: Split pages

### ISSUE THREAD

**Issue by XiangZhao969** [MCrafterss/MHelpModifer#2]
since there are too much infomation in the config, players unable to read them all, this plugin would be awesome if support split pages like /help 2 /help 3...

**Comment by PocketKiller** [comment]
Added to TODO

**Comment by Tolo0** [comment]
I like this plugin. Will be using it when split pages is available.  Good work.

**Comment by PocketKiller** [comment]
test it?

**Comment by Tolo0** [comment]
[CRITICAL]: Unhandled exception executing command 'help' in help: Undefined offset: 02016-02-02 [13:35:11] [NOTICE]: ArrayOutOfBoundsException: "Undefined offset: 0" (E_NOTICE) in "/MHelpModifer_v2.phar/src/MCrafters/HelpModifer/command/ModifedHelpCommand" at line 44 2016-02-02 [13:35:24] [CRITICAL]: Unhandled exception executing command 'help' in help: Undefined offset: 0

**Comment by PocketKiller** [comment]
what line?

**Comment by Tolo0** [comment]
![screenshot_2016-02-02-18-30-03](https://cloud.githubusercontent.com/assets/13458191/12760027/35d51534-c9dc-11e5-808e-f0b7d8fa8001.png)

**Comment by PocketKiller** [comment]
what line?

**Comment by Tolo0** [comment]
Line 44

**Comment by PocketKiller** [comment]
try it now.

**Comment by Tolo0** [comment]
When doing /help. 
Nothing at all shows. No error, unknown commands or anything. Just blank. And on console it shows the plugin working.

**Comment by PocketKiller** [comment]
hmm... I want to debug, try /help 1

**Comment by Tolo0** [comment]
Nope doesn't show anything.

**Comment by Tolo0** [comment]
Help doesn't even work on console.

**Comment by PocketKiller** [comment]
I am working

**Comment by Tolo0** [comment]
Np. Let me know if you need help.

**Comment by Tolo0** [comment]
Need any testing?

**Comment by Tolo0** [comment]
Any luck getting it working?

**Comment by PocketKiller** [comment]
not yet

**Comment by Tolo0** [comment]
Ok. Sorry for harassing u. I'm just excited about using this plugin 😅

**Comment by Vaivez66** [comment]
Will you continue this project, PocketKiller?

**Comment by ghost** [comment]
@Tolo0 MULTI PAGE SUPPORT added! ;)
Also I fixed many bugs

Download now at [https://github.com/MCrafterss/MHelpModifer/releases](url)

**Comment by ghost** [comment]
Added unlimited pages support in v3.1 ok
